// <auto-generated />
using BornoBit.Restaurant.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace BornoBit.Restaurant.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260614110000_AddTableHold")]
    partial class AddTableHold
    {
        // NOTE: This migration was hand-authored because both host apps were running and held a lock on the
        // build output, so `dotnet ef migrations add` could not produce the file. The Up/Down operations and
        // the updated ApplicationDbContextModelSnapshot are authoritative and apply correctly at runtime.
        // BuildTargetModel is intentionally left empty (it is not consulted when applying explicit operations);
        // regenerate this migration with the EF tools when the apps are stopped to repopulate it if desired.
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
        }
    }
}
